security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory:
          memory:
            users:
              admin:
                password: password
                roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern:                ^/(_(profiler|wdt)|css|images|js)/
            security:               false
        main:
            # pattern:                ^/
            anonymous:              true
            form_login:
              check_path:           security_login
              login_path:           security_login
              csrf_token_generator: security.csrf.token_manager
              default_target_path:  admin
            logout:
              path:                 security_logout
              target:               /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
