vich_uploader:
    db_driver: orm

    mappings:
       image_produit:
           uri_prefix: '%app.path.image_produit%'
           upload_destination: '%kernel.project_dir%/public%app.path.image_produit%'
           namer: vich_uploader.namer_origname
